wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.13
    t:
      1:
      - 1
      4: 3.6.13
      5: 0.11.0
      8:
      - 2
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 2
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: yolov5/yolov5/models/yolov5s.yaml
data:
  desc: null
  value: ./yolov5/yolov5/data/coco128.yaml
data_dict:
  desc: null
  value:
    download: https://github.com/ultralytics/yolov5/releases/download/v1.0/coco128.zip
    names:
    - Port
    - Airport
    nc: 2
    path: /media/data/data02/yb_data/train_data_1024/
    test: null
    train: train.txt
    val: val.txt
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 5
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 2
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: yolov5/yolov5/models/yolov5s.yaml
    data: ./yolov5/yolov5/data/coco128.yaml
    device: ''
    entity: null
    epochs: 5
    evolve: null
    exist_ok: false
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      copy_paste: 0.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.01
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 1.0
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    imgsz: 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    noval: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/exp6
    save_period: -1
    single_cls: false
    sync_bn: false
    upload_dataset: false
    weights: yolov5s.pt
    workers: 8
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp6
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 8
